// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsuqipicecfqypyhvjum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzdXFpcGljZWNmcXlweWh2anVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNDExOTcsImV4cCI6MjA1NjgxNzE5N30.Z6ABr67l9uV96RDr75sQdX11KgAVHId4zyhD49RvfCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);